spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kioskdb
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      # Optional - comment out if Redis not installed

server:
  port: 8080

cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173"
